spring:
  redis:
    host: 120.24.25.238
    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-wait: 2000
        max-idle: 8
        min-idle: 0
    timeout: 5000
